### ISSUE TITLE
For historical compatibility issues, we still rely on ancient geronimo https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/main/external/geronimo_javamail/pom.xml#L47

### ISSUE THREAD

**Issue by SeeYaaG** [GoogleCloudPlatform/appengine-java-standard#114]
For historical compatibility issues, we still rely on ancient geronimo https://github.com/GoogleCloudPlatfo
![1000077626](https://user-images.githubusercontent.com/133252985/326505975-c1b0b1e4-c67a-4262-8480-8e6874197aba.jpg)
rm/appengine-java-standard/blob/main/external/geronimo_javamail/pom.xml#L47

Might be time to revisit this dep for EE 10, looking at it...

_Originally posted by @ludoch in https://github.com/GoogleCloudPlatform/appengine-java-standard/issues/109#issuecomment-2083039419_

**Comment by ludoch** [comment]
How is this one different than https://github.com/GoogleCloudPlatform/appengine-java-standard/issues/109 ?
