### ISSUE TITLE
Build failure when building with -T option for parallel build

### ISSUE THREAD

**Issue by lachlan-roberts** [GoogleCloudPlatform/appengine-java-standard#16]
When building the project with parallel build: 
```
mvn clean install -DskipTests -T 1C
```

I see `BUILD FAILURE`:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.2.0:unpack (unpack) on project appengine-java-sdk: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]

**Comment by lachlan-roberts** [comment]
@olamy any idea how this could be fixed?

**Comment by olamy** [comment]
should be fixed with https://github.com/GoogleCloudPlatform/appengine-java-standard/pull/17
