### ISSUE TITLE
runtime-deployment is not built properly

### ISSUE THREAD

**Issue by lachlan-roberts** [GoogleCloudPlatform/appengine-java-standard#22]
when I run `mvn clean install -DskipTests` I can build the project and it do see
```
[INFO] AppEngine :: runtime-deployment 2.0.11-SNAPSHOT .... SUCCESS [  1.771 s]
```

However I should be seeing jars inside of the `runtime/deployment/target/runtime-deployment-2.0.11-SNAPSHOT` directory.

If I then run `mcist -pl :runtime-deployment` I now see `runtime-impl.jar`, `runtime-main.jar` and `runtime-shared.jar` inside of this directory.

**Comment by ludoch** [comment]
Right, I see only the targz and zip files which contain the correct 3 jars....

**Comment by ludoch** [comment]
The deployment file contains
```  <formats>
    <format>zip</format>
    <format>tar.gz</format>
    <format>dir</format>
  </formats>
```

so we should see the dir/ and we do not...
