### ISSUE TITLE
Flood of java.io.IOException when disabling Cloud Debugger on Java11 Standard Runtime

### ISSUE THREAD

**Issue by ccYHM86** [GoogleCloudPlatform/appengine-java-standard#24]
Our organization is currently in the process of migrating to the Java11 App Engine Standard Runtime (currently we are on the Java8 App Engine Standard Runtime). It appears the Java11 Runtime makes use of the Google Cloud Debugger Service. According to the [Cloud Debugger Docs](https://cloud.google.com/stackdriver/docs/deprecations/debugger-deprecation?_gl=1*1xeyfqo*_ga*NDMxODY4MDk3LjE2NjExOTQ0MjQ.*_ga_WH2QY8WWF5*MTY4NjI1NDg4Ny4zMDYuMS4xNjg2MjU1Mzg3LjAuMC4w&_ga=2.63429226.-431868097.1661194424) this API is deprecated and the service is shutdown as of May 31, 2023. 

When we disable the API in Google Cloud we see a flood of the following Error

`
textPayload: "java.io.IOException: Server returned HTTP response code: 403 for URL: https://clouddebugger.googleapis.com/v2/controller/debuggees/register
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at com.google.devtools.cdbg.debuglets.java.GcpHubClient.registerDebuggee(Unknown Source)"
`

It does not seem like this error is impacting our application however it is very verbose and flooding our logs making it more difficult to perform basic debugging/troubleshooting (without having to manually exclude them).

We do not see this error when the Cloud Debugger API is disabled and we are running on the Java8 Runtime. Therefore it seems like this is specific to the Java11 Runtime. I searched and could not find any documentation on how to resolve this. Does the Java11 runtime need an update to configure it to not use the Cloud Debugger?

Any help would be appreciated.  

Thanks

**Comment by ludoch** [comment]
Hi,
What is the timestamp of this log entry?
The debugger removal push should be now done in prod.
Do you still see the error now?

**Comment by ccYHM86** [comment]
Wow, thanks for the quick reply @ludoch . This is happening right now:

![image](https://github.com/GoogleCloudPlatform/appengine-java-standard/assets/95307271/ecc5340a-a566-43e7-98c7-602957f147eb)

We are using the legacy bundled services (so still appengine-web.xml). Let me check to see if we are perhaps explicitly telling the app to use the debugger.

**Comment by ludoch** [comment]
You are correct, I also see this in one of my logs:
[serve] Running /bin/sh -c exec java -showversion -Xms32M -Xmx307M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:+PrintCommandLineFlags -agentpath:/opt/cdbg/cdbg_java_agent.so=--log_dir=/tmp,--alsologtostderr=true,--cdbg_extra_class_path=/workspace/WEB-INF/classes:/workspace/WEB-INF/lib --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.logging/java.util.logging=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED -Dclasspath.runtimebase=/base/java_runtime -Djava.class.path=/base/java_runtime/runtime-main.jar -Djava.library.path=/base/java_runtime: com/google/apphosting/runtime/JavaRuntimeMainWithDefaults --fixed_application_path=/workspace /base/java_runtime

so the buildpacks PR that removed it is still not in prod!
Looking more.

**Comment by ccYHM86** [comment]
Ok, thanks @ludoch. Please advise if possible on a timeline for getting this change into prod.

**Comment by ludoch** [comment]
Meanwhile, keep the debugger API active... It is complex to coordinate all the releases with multiple layers.

**Comment by ccYHM86** [comment]
Thanks @ludoch we can keep the debugger API active for now. My only concern with that approach is that according to Google Cloud Debugger docs that service is [deprecated and should be shut down](https://cloud.google.com/stackdriver/docs/deprecations/debugger-deprecation?_gl=1*1xeyfqo*_ga*NDMxODY4MDk3LjE2NjExOTQ0MjQ.*_ga_WH2QY8WWF5*MTY4NjI1NDg4Ny4zMDYuMS4xNjg2MjU1Mzg3LjAuMC4w&_ga=2.63429226.-431868097.1661194424) by now.

I fully understand the complexity of these types of releases, it would be nice to be able to roll this change out (without having to rely on the Cloud Debugger) sometime before August. I will continue to watch this space for updates.

**Comment by shreejad** [comment]
Update: We are working on releasing the fix for these errors. Java 17 should be working fine, the issue was solely with Java 11. ETA for fix is end of day.

**Comment by ccYHM86** [comment]
@shreejad perfect. I can re-test once the change is re-deployed. Please update this space once complete. Thanks

**Comment by shreejad** [comment]
@ccYHM86 This should be resolved now.

**Comment by ludoch** [comment]
yes, thanks!

**Comment by ccYHM86** [comment]
Thanks @ludoch and @shreejad. I can confirm from my end I am no longer seeing this error when deploying my app in the Java11 Standard Env and the Cloud Debugger API is disabled. Thanks for the quick turnaround.
