### ISSUE TITLE
add tests for error page mappings

### ISSUE THREAD

**Issue by lachlan-roberts** [GoogleCloudPlatform/appengine-java-standard#318]
After issue https://github.com/GoogleCloudPlatform/appengine-java-standard/issues/316 it is clear that there is insufficient testing for error page mappings in `web.xml`.

This test should be parameterized over the various Jetty & HTTP/RPC modes.

Adding tests in this area will help to prevent future regressions.

**Comment by srinjoyray** [comment]
Fixed with PR - https://github.com/GoogleCloudPlatform/appengine-java-standard/pull/324
